import Config

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :ollama_chat, OllamaChatWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "hIXSHzrKB7nPdudysq9fcTi2JV+rs1roPLXfleR7Wv22ab8Xj/TeHrhiXjnSGRrO",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:ollama_chat, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:ollama_chat, ~w(--watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Reload browser tabs when matching files change.
config :ollama_chat, OllamaChatWeb.Endpoint,
  live_reload: [
    web_console_logger: true,
    patterns: [
      # Static assets, except user uploads
      ~r"priv/static/(?!uploads/).*\.(js|css|png|jpeg|jpg|gif|svg)$"E,
      # Gettext translations
      ~r"priv/gettext/.*\.po$"E,
      # Router, Controllers, LiveViews and LiveComponents
      ~r"lib/ollama_chat_web/router\.ex$"E,
      ~r"lib/ollama_chat_web/(controllers|live|components)/.*\.(ex|heex)$"E
    ]
  ]

# Enable dev routes for dashboard and mailbox
config :ollama_chat, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include debug annotations and locations in rendered markup.
  # Changing this configuration will require mix clean and a full recompile.
  debug_heex_annotations: true,
  debug_attributes: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true

# Disable swoosh api client as it is only required for production adapters.
config :swoosh, :api_client, false

# MCP (Model Context Protocol) Configuration for Development
config :ollama_chat, :mcp_enabled, true

mcpctl = Path.join([__DIR__, "..", "mcp_test_server", "mcpctl"]) |> Path.expand()

config :ollama_chat, :mcp_servers, [
  # ── Filesystem ─────────────────────────────────────────────────────────────
  # 17 tools: read/write/list/search files, batch copy/move/delete operations.
  # Scoped to ~/mcp_workspace. Destructive operations require approval.
  %{
    name: :mcp_filesystem,
    display_name: "MCP Filesystem",
    description: "File operations within the MCP workspace (17 tools)",
    command: mcpctl,
    args: ["filesystem"],
    enabled: true,
    requires_approval: false,
    dangerous_tools: [
      "write_file",
      "create_directory",
      "move_file",
      "copy_file",
      "delete_file",
      "delete_directory",
      "delete_files",
      "delete_directories",
      "delete_files_by_pattern",
      "delete_directories_by_pattern",
      "move_files",
      "copy_files"
    ]
  },

  # ── Memory ─────────────────────────────────────────────────────────────────
  # 4 tools: memory_set, memory_get, memory_delete, memory_list.
  # In-memory KV store with optional TTL. Scoped to server process lifetime.
  %{
    name: :mcp_memory,
    display_name: "MCP Memory",
    description: "In-memory key/value store with optional TTL (4 tools)",
    command: mcpctl,
    args: ["memory"],
    enabled: true,
    requires_approval: false,
    dangerous_tools: []
  },

  # ── System ─────────────────────────────────────────────────────────────────
  # 12 tools: BEAM VM monitoring (memory, processes, schedulers, ETS, apps),
  # environment variable inspection, and general utilities (echo, time, hash).
  %{
    name: :mcp_system,
    display_name: "MCP System",
    description: "BEAM monitoring, environment variables, and utilities (12 tools)",
    command: mcpctl,
    args: ["system"],
    enabled: true,
    requires_approval: false,
    # Env inspection can expose secrets; require approval for those tools
    dangerous_tools: ["list_env", "get_env"]
  },

  # ── Web ────────────────────────────────────────────────────────────────────
  # 1 tool: web_search via DuckDuckGo Instant Answer API (no API key required).
  %{
    name: :mcp_web,
    display_name: "MCP Web",
    description: "Web search via DuckDuckGo Instant Answers (1 tool)",
    command: mcpctl,
    args: ["web"],
    enabled: true,
    requires_approval: false,
    dangerous_tools: []
  }
]
